CLI-11 Add ability to use plain text aws sso token from aws/sso/cache dir if available.
common-fate/granted pull request #253
Opened 2022-09-14 06:15 UTC by Eddie023

2022-09-14 07:26 UTC, chrnorm requested changes
Thanks for this @Eddie023! I've left some review comments.

A quick question, are we using this schema for AWS profiles?
```
[profile admin]
granted_sso_start_url = https://example.awsapps.com/start
granted_sso_region = ap-southeast-2
granted_sso_account_name = Testing
granted_sso_account_id = 123456789012
granted_sso_role_name = GrantedAdministratorAccess
region = ap-southeast-2
credential_process = granted credential-process --profile admin --url https://granted.example.com
```

From my review of the PR, it appears that we are using
```
[profile admin]
sso_start_url = https://example.awsapps.com/start
sso_region = ap-southeast-2
sso_account_name = Testing
sso_account_id = 123456789012
sso_role_name = GrantedAdministratorAccess
region = ap-southeast-2

[profile granted.admin]
credential_process = granted credential-process --profile admin --url https://granted.example.com
```

This leads to an undesired effect as users might use `aws s3 ls --profile admin` and then they receive the same error we're trying to improve upon:
```
operation error SSO: GetRoleCredentials, https response error StatusCode: 403, RequestID: a41b0ac7-56bb-439c-acc6-6594d1532e62, api error ForbiddenException: No access
```

CC @jordiup

2022-09-14 07:26 UTC, chrnorm commented on pkg/cfaws/profiles.go
> +	IsDefaultCredential bool
can we call this something like `UsePlaintextSSOToken`? Just thinking that "default" is a bit confusing, as Granted CLI defaults to using the keychain, whereas "default" in this context means "don't use the keychain".

```suggestion
	UsePlaintextSSOToken bool
```

2022-09-14 07:26 UTC, chrnorm commented on pkg/granted/credentialsprocess.go
> +		}
can we remove this check? if this function is being called, it means that the user has correctly set up their credential process, so it doesn't matter what their profile is named. This forces advanced users who might want to name their profiles a different way to use our `granted.` naming scheme.

```suggestion
```

2022-09-14 07:26 UTC, chrnorm commented on pkg/granted/credentialsprocess.go
> +			log.Fatal(err)
Is there any specific need here to use log.Fatal? If we return `err`, `urfav/cli` should log the error for us!

```suggestion
			return err
```

2022-09-19 04:24 UTC, Eddie023 commented on pkg/cfaws/assumer_aws_sso.go
> +	shouldSilentStdout := ctx.Value("shouldSilentStdout")
I think there is a better way to pass value to context. Suggestions appreciated.

2022-09-20 06:03 UTC, jordiup approved these changes
Looks good @Eddie023, happy for this one to merge into `connecting-to-approvals`. We'll do another round of UAT 👌

2022-09-20 06:21 UTC, merged