add config opt to skip shell alias
common-fate/granted pull request #495
Opened 2023-09-22 05:24 UTC by Eddie023

### What changed?

### Why?

### How did you test it?

### Potential risks

### Is patch release candidate?

### Link to relevant docs PRs

2023-09-27 17:35 UTC, chrnorm commented on cmd/granted/main.go
> +		app = assume.GetCliApp(assume.ConfigOpts{ShouldSkipShellAlias: false})
@Eddie023 can ShouldSkipShellAlias be removed now? it looks like you're setting it to `false` anyway

2023-10-03 01:29 UTC, JoshuaWilkes requested changes

2023-10-03 01:29 UTC, JoshuaWilkes commented on pkg/launcher/console.go
> +type Console struct {
rename this to CommonFate

2023-10-03 01:29 UTC, JoshuaWilkes commented on pkg/browser/browsers.go
> +	ConsoleKey           string = "CONSOLE"
```suggestion
	CommonFateKey           string = "COMMONFATE"
```

2023-10-03 01:45 UTC, JoshuaWilkes approved these changes

2023-10-04 17:09 UTC, chrnorm approved these changes

2023-10-13 05:39 UTC, JoshuaWilkes approved these changes

2023-10-13 05:39 UTC, merged