A bit of code refactoring
common-fate/granted pull request #805
Opened 2024-11-15 09:48 UTC by EloyTolosaDev

It started because I wanted to investigate on issue #785 , and I ended up refactoring the codebase a bit while working on it. In the end, I did nothing about the issue because I couldn't figure out what was happening, and I did not get any response from the person who created the issue, so I could not investigate further. After all, it looks like a user problem, as I was unable to reproduce the problem.

### What changed?
Functionality did not change, the main changes were:
1. Removing  an unused function "IsOutdatedConfig" as it was only checking if the length of the variable ProfileRegistryURLs and that could be done separately without any function.
2. Removed an unused error variable "RegistrySyncError" as it did not provide any extra functionality in the case of the error ocurred, also it was not being used.
3. Removed the awsmerge.Merger struct, and replacing the merger struct functions as package functions, as there were no differences and having an extra awsmerge.Merger struct which did nothing at all looked strange to me.

### Why?

### How did you test it?
I tested the dassume and dgranted binaries and worked as espected.

### Potential risks

### Is patch release candidate?

### Link to relevant docs PRs

2025-02-03 16:04 UTC, chrnorm requested changes
Thanks for this contribution @EloyTolosaDev! One requested change here

2025-02-03 16:04 UTC, chrnorm commented on pkg/autosync/autosync.go
> +	if len(registries) > 0 {
`registry.IsOutdatedConfig()` checks a different field in the Granted config to the one in `registry.GetProfileRegistries()`.

IsOutdatedConfig checks if the length of `ProfileRegistryURLS` is > 0, whereas `GetProfileRegistries` uses the `ProfileRegistry` field.

The change you have made here will cause valid profile registry configuration to return the error. Could you please restore the previous behaviour? 

In this instance, I'd propose just restoring the `registry.IsOutdatedConfig` function and restoring the call to the function. The code there was working in production, so there is no need to change it IMO.

2025-02-04 07:55 UTC, EloyTolosaDev commented
Hi! Thanks for the response. I checked what you said and you're totally true, I was confused about profileRegistryURLs field and the actual loadedRegistry structs.
I changed and checked that so now everything should be ok.

Kind regards

2025-05-11 14:57 UTC, chrnorm approved these changes
Thankyou @EloyTolosaDev!

2025-05-11 15:00 UTC, merged